### ISSUE TITLE
Priority issue: Horizontal scroll not visible

### ISSUE THREAD

**Issue by Yavnikaa** [IMGIITRoorkee/chakra-library#219]
https://iitr.ac.in/Departments/Electrical%20Engineering%20Department/People/Faculty/100083.html

iss page pr miscellaneous tab mei horizontal scroll hai but wo visibile nahi hai

@achintyanath can you pls fix this?

**Comment by saurabhhere** [comment]
Fixed in [6129d89](https://github.com/IMGIITRoorkee/chakra-library/commit/6129d89214805697020f446532be141ca1649e4b)
